CREATE PROCEDURE [dbo].[TestSuite_Delete](@TestSuiteId BIGINT)
AS
BEGIN
	SET NOCOUNT ON

	BEGIN TRY
		DELETE FROM TestSuite
		WHERE TestSuiteId = @TestSuiteId
	END TRY
	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ErrorNumber,
			ERROR_MESSAGE() AS ErrorMessage;
	END CATCH
END